foreground            #f8f8f2
background            #282a36
selection_foreground  #44475a
selection_background  #ff79c6

url_color             #282a36

# Black
color8   #f8f8f2
color0   #21222c

# Red
color1   #f452b3
color9   #4b4559

# Green
color2   #00f5f3
color10  #4b4559

# Yellow
color3   #ffeef4
color11  #4b4559

# Blue
color4   #bd93f9
color12  #4b4559

# Magenta
color5   #e980f0
color13  #4b4559

# Cyan
color6   #cddbff
color14  #4b4559

# White
color15  #6272a4
color7   #f8f8f2

# Cursor colors
cursor #f8f8f2
cursor_text_color #21222c

# Tab bar colors
active_tab_foreground #282a36
active_tab_background #bd93f9
inactive_tab_foreground #f8f8f2
inactive_tab_background #44475a

# Marks
mark1_foreground #282a36
mark1_background #bd93f9
mark2_foreground #282a36
mark2_background #ff79c6
mark3_foreground #282a36
mark3_background #ffb86c

# Splits/Windows
active_border_color #bd93f9
inactive_border_color #282a36
bell_border_color #ff5a00
