foreground            #e7e0e8
background            #151218
selection_foreground  #4c4357
selection_background  #cec2da

url_color             #6b538c

# Black
color8   #e7e0e8
color0   #151218

# Red
color1   #f452b3
color9   #643663

# Green
color2   #00b7d0
color10  #2b4772

# Yellow
color3   #ffdfd4
color11  #683652

# Blue
color4   #bf95fe
color12  #523c73

# Magenta
color5   #ea72f6
color13  #5b396d

# Cyan
color6   #9ccaff
color14  #38466e

# White
color15  #ccc4cf
color7   #e7e0e8

# Cursor colors
cursor #e7e0e8
cursor_text_color #151218

# Tab bar colors
active_tab_foreground #3b255b
active_tab_background #d6bbfb
inactive_tab_foreground #eddcff
inactive_tab_background #523c73

# Marks
mark1_foreground #250e44
mark1_background #eddcff
mark2_foreground #20182a
mark2_background #ebddf7
mark3_foreground #321019
mark3_background #ffd9df

# Splits/Windows
active_border_color #d6bbfb
inactive_border_color #3b255b
bell_border_color #ff5a00
