cursor #ffffff
cursor_text_color #dddddd

foreground            #e3e3e3
background            #1e1e1e
selection_foreground  #443b51
selection_background  #d0c4dc
url_color             #5f3a93

# black
color8   #ffffff
color0   #1e1e1e

# red
color1   #ffd3cd
color9   #ff574c

# green
color2   #e6d8f2
color10  #9d90a8

# yellow
color3   #ffd2d9
color11  #bd8791

# blue
color4   #e9d5ff
color12  #a883dc

# magenta
color5   #eddcff
color13  #d8bbff

# cyan
color6   #ffdae0
color14  #f4b9c4

# white
color15  #dddddd
color7   #e3e3e3
