$image = {{ image }}
<* for name, value in colors *>
${{ name }} = rgba({{ value.default.hex_stripped | to_color | harmonize: {{ colors.source_color.default.hex_stripped | to_color }} | auto_lightness: 10.0 }}ff)
<* endfor *>
