[[mgr.prepend_keymap]]
on = ["g", "d"]
run = "cd ~/Downloads"
desc = "Cd to ~/Downloads"

[[mgr.prepend_keymap]]
on = ["g", "p"]
run = "cd ~/Pictures"
desc = "Cd to ~/Pictures"

[[mgr.prepend_keymap]]
on = ["g", "P"]
run = "cd ~/Projects"
desc = "Cd to ~/Projects"

[[mgr.prepend_keymap]]
on = "!"
for = "unix"
run = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"

[[mgr.prepend_keymap]]
on = "y"
run = [
  'shell -- for path in %s; do echo "file://$path"; done | wl-copy -t text/uri-list',
  "yank",
]

[[mgr.prepend_keymap]]
on = ["g", "r"]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'

[[mgr.prepend_keymap]]
on = ["c", "a", "a"]
run = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on = ["c", "a", "p"]
run = "plugin compress -p"
desc = "Archive selected files (password)"

[[mgr.prepend_keymap]]
on = ["c", "a", "h"]
run = "plugin compress -ph"
desc = "Archive selected files (password+header)"

[[mgr.prepend_keymap]]
on = ["c", "a", "l"]
run = "plugin compress -l"
desc = "Archive selected files (compression level)"

[[mgr.prepend_keymap]]
on = ["c", "a", "u"]
run = "plugin compress -phl"
desc = "Archive selected files (password+header+level)"

[[mgr.prepend_keymap]]
on = [",", "s"]
run = "plugin what-size"
desc = "Calc size of selection or cwd"

[[mgr.prepend_keymap]]
on = ["g", "i"]
run = "plugin lazygit"
desc = "run lazygit"

[[mgr.prepend_keymap]]
on = ["g", "l"]
run = "plugin open-git-remote"
desc = "open git remote url"

[[mgr.prepend_keymap]]
on = "o"
run = "plugin open-with-cmd -- block"
desc = "Open with command in the terminal"

[[mgr.prepend_keymap]]
on = "<C-o>"
run = "plugin open-with-cmd"
desc = "Open with command"

[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on = "<C-w>"
for = "linux"
run =[
  "shell -- hyprctl hyprpaper wallpaper ,%h",
  "shell -- matugen --type scheme-content --source-color-index 0 image %h"
] 
desc = "Set hovered file as wallpaper"

[[mgr.prepend_keymap]]
on   = [ "g", "f" ]
run  = 'search_do --via=fd --args="-d 3"'
desc = "Switch to the flat view with a max depth of 3"

[[mgr.prepend_keymap]]
on   = "<C-g>"
run  = 'shell -- rofi -theme fullscreen-preview -show filebrowser -filebrowser-command "ya emit reveal" -filebrowser-directory "$(pwd)"'
desc = "Grid view"
