# If the user's terminal is in dark mode, Yazi will load `theme-dark.toml` on startup; otherwise, `theme-light.toml`.
# You can override any parts of them that are not related to the dark/light mode in your own `theme.toml`.

# If you want to dynamically override their content based on dark/light mode, you can specify two different flavors
# for dark and light modes under `[flavor]`, and do so in those flavors instead.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

# : Flavor [[[

[flavor]
dark  = ""
light = ""

# : ]]]


# : App [[[

[app]
overall = {}

# : ]]]


# : Manager [[[

[mgr]
cwd = { fg = "#fff2ef" }

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Symlink
symlink_target = { italic = true }

# Marker
marker_copied = { fg = "#7296ff", bg = "#7296ff" }
marker_cut = { fg = "#d8e2ff", bg = "#d8e2ff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#adc6ff", bg = "#adc6ff" }

# Count
count_copied = { fg = "#001a41", bg = "#d8e2ff" }
count_cut = { fg = "#001a41", bg = "#d8e2ff" }
count_selected = { fg = "#470800", bg = "#adc6ff" }

# Border
border_symbol = " "
border_style  = { fg = "#ffb4a4" }

# : ]]]


# : Tabs [[[

[tabs]
active = { bg = "#ffb4a4", fg = "#470800", bold = true }
inactive  = { bg = "#5d3f39", fg = "#e7bdb4" }

# Separator
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# : ]]]


# : Mode [[[

[mode]
normal_main = { bg = "#ffb4a4", fg = "#470800", bold = true }
normal_alt  = { bg = "#5d3f39", fg = "#e7bdb4" }

# Select mode
select_main = { bg = "#ffb4a4", fg = "#470800", bold = true }
select_alt  = { bg = "#5d3f39", fg = "#e7bdb4" }

# Unset mode
unset_main = { bg = "#adc6ff", fg = "#001f4b", bold = true }
unset_alt  = { bg = "#5d3f39", fg = "#e7bdb4" }

# : ]]]


# : Indicator of hovered file [[[

[indicator]
parent  = { bg = "#ffb4a4", fg = "#470800", reversed = true }
current = { bg = "#ffb4a4", fg = "#470800", bold = true }
preview = { underline = true }
padding = { open = "", close = "" }

# : ]]]


# : Status bar [[[

[status]
overall   = {}
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep = { fg = "#ff593a" }
perm_type = { fg = "#ff360b" }
perm_read = { fg = "#3f70ff" }
perm_write = { fg = "#145cff" }
perm_exec = { fg = "#ff2b12" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb4a4", bg = "#513b36" }
progress_error = { fg = "#ffb4ab", bg = "#513b36" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#513b36" }
cand = { fg = "#ffb4a4" }
rest = { fg = "#470800" }
desc = { fg = "#fff2ef" }
separator = " ▶ "
separator_style = { fg = "#fff2ef" }

# : ]]]


# : Confirmation [[[

[confirm]
border = { fg = "#ffb4a4" }
title = { fg = "#fff2ef" }
body       = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# : ]]]


# : Spotter [[[

[spot]
border = { fg = "#ffb4a4" }
title = { fg = "#fff2ef" }

# Table
tbl_col  = { fg = "#fff2ef" }
tbl_cell = { fg = "#fff2ef", reversed = true }

# : ]]]


# : Notification [[[

[notify]
title_info = { fg = "#adc6ff" }
title_warn = { fg = "#ffb4a4" }
title_error = { fg = "#ffb4ab" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#ffb4a4" }
active = { fg = "#adc6ff", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb4a4" }
title    = {}
value = { fg = "#fff2ef" }
selected = { reversed = true }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#ffb4a4", bg = "#470800" }
active   = { reversed = true }
inactive = {}

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb4a4" }
title = {}
hovered = { fg = "#d8e2ff", underline = true }

# : ]]]


# : Help menu [[[

[help]
on = { fg = "#fff2ef" }
run = { fg = "#fff2ef" }
desc    = {}
hovered = { reversed = true, bold = true }
footer = { fg = "#470800", bg = "#ffb4a4" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#da342e" },
    { name = "*", is = "exec", fg = "#ffffff" },

    # Fallback
    { name = "*", fg = "#fff2ef" },
    { name = "*/", fg = "#ffb4a4" },
]

# : ]]]
