# If the user's terminal is in dark mode, Yazi will load `theme-dark.toml` on startup; otherwise, `theme-light.toml`.
# You can override any parts of them that are not related to the dark/light mode in your own `theme.toml`.

# If you want to dynamically override their content based on dark/light mode, you can specify two different flavors
# for dark and light modes under `[flavor]`, and do so in those flavors instead.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

# : Flavor [[[

[flavor]
dark  = ""
light = ""

# : ]]]


# : App [[[

[app]
overall = {}

# : ]]]


# : Manager [[[

[mgr]
cwd = { fg = "#ffffff" }

# Find
find_keyword = { fg = "#ffd3cd", bold = true, italic = true, underline = true }
find_position = { fg = "#ffd3cd", bold = true, italic = true }

# Symlink
symlink_target = { italic = true }

# Marker
marker_copied = { fg = "#b576ff", bg = "#b576ff" }
marker_cut = { fg = "#ecdcff", bg = "#ecdcff" }
marker_marked = { fg = "#ffd3cd", bg = "#ffd3cd" }
marker_selected = { fg = "#e8d6ff", bg = "#e8d6ff" }

# Count
count_copied = { fg = "#240054", bg = "#ecdcff" }
count_cut = { fg = "#240054", bg = "#ecdcff" }
count_selected = { fg = "#003d36", bg = "#e8d6ff" }

# Border
border_symbol = " "
border_style  = { fg = "#69decd" }

# : ]]]


# : Tabs [[[

[tabs]
active = { bg = "#80f2e2", fg = "#003d36", bold = true }
inactive  = { bg = "#455250", fg = "#d3e0dc" }

# Separator
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# : ]]]


# : Mode [[[

[mode]
normal_main = { bg = "#80f2e2", fg = "#003d36", bold = true }
normal_alt  = { bg = "#455250", fg = "#d3e0dc" }

# Select mode
select_main = { bg = "#bce7df", fg = "#003d36", bold = true }
select_alt  = { bg = "#455250", fg = "#d3e0dc" }

# Unset mode
unset_main = { bg = "#e8d6ff", fg = "#3a166d", bold = true }
unset_alt  = { bg = "#455250", fg = "#d3e0dc" }

# : ]]]


# : Indicator of hovered file [[[

[indicator]
parent  = { bg = "#80f2e2", fg = "#003d36", reversed = true }
current = { bg = "#80f2e2", fg = "#003d36", bold = true }
preview = { underline = true }
padding = { open = "", close = "" }

# : ]]]


# : Status bar [[[

[status]
overall   = {}
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep = { fg = "#0bdbbb" }
perm_type = { fg = "#4bbfa9" }
perm_read = { fg = "#9943ff" }
perm_write = { fg = "#923dff" }
perm_exec = { fg = "#ff4c34" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#80f2e2", bg = "#484f4d" }
progress_error = { fg = "#ffd3cd", bg = "#484f4d" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#484f4d" }
cand = { fg = "#80f2e2" }
rest = { fg = "#003d36" }
desc = { fg = "#ffffff" }
separator = " ▶ "
separator_style = { fg = "#ffffff" }

# : ]]]


# : Confirmation [[[

[confirm]
border = { fg = "#80f2e2" }
title = { fg = "#ffffff" }
body       = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# : ]]]


# : Spotter [[[

[spot]
border = { fg = "#80f2e2" }
title = { fg = "#ffffff" }

# Table
tbl_col  = { fg = "#ffffff" }
tbl_cell = { fg = "#ffffff", reversed = true }

# : ]]]


# : Notification [[[

[notify]
title_info = { fg = "#e8d6ff" }
title_warn = { fg = "#80f2e2" }
title_error = { fg = "#ffd3cd" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#80f2e2" }
active = { fg = "#e8d6ff", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#80f2e2" }
title    = {}
value = { fg = "#ffffff" }
selected = { reversed = true }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#80f2e2", bg = "#003d36" }
active   = { reversed = true }
inactive = {}

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#80f2e2" }
title = {}
hovered = { fg = "#ecdcff", underline = true }

# : ]]]


# : Help menu [[[

[help]
on = { fg = "#ffffff" }
run = { fg = "#ffffff" }
desc    = {}
hovered = { reversed = true, bold = true }
footer = { fg = "#003d36", bg = "#bce7df" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#ff574c" },
    { name = "*", is = "exec", fg = "#000000" },

    # Fallback
    { name = "*", fg = "#ffffff" },
    { name = "*/", fg = "#69decd" },
]

# : ]]]
