# -----------------------------------------------------
# Animations
# https://wiki.hypr.land/Configuring/Variables/#animations
# -----------------------------------------------------

source = ~/.config/hypr/configs/animations/horizontal_bounce.conf
