# -----------------------------------------------------
# Auto-Start
# -----------------------------------------------------

# Start Polkit
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Load Wallpaper
# exec-once = hyprpaper

# Load Waybar
exec-once = waybar

# Load Notification Daemon
exec-once = swaync

# Using hypridle to start hyprlock
exec-once = hypridle

# Load power profile manager
exec-once = ~/.config/hypr/scripts/power-monitor.sh

# Load cliphist history
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data

# Uncomment in case you have issues with screensharing
# exec-once = ~/.config/hypr/scripts/xdg.sh
