#################
### AUTOSTART ###
#################

exec-once = uwsm app -- swaync
# exec-once = uwsm app -- hypridle
exec-once = uwsm app -- waybar
exec-once = uwsm app -- hyprpaper

exec-once = uwsm app -- wl-paste --type text --watch cliphist store
exec-once = uwsm app -- wl-paste --type image --watch cliphist store

exec-once = [workspace special:btop silent] uwsm app -- kitty --class btop-monitor -e btop

# portals launch after this gets executed
# exec-once = $HOME/.config/hypr/scripts/xdph.sh
# exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = uwsm finalize
