# -----------------------------------------------------
# Auto-Start
# -----------------------------------------------------

exec-once = uwsm app -- /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = uwsm app -- swaync
exec-once = uwsm app -- hypridle
exec-once = uwsm app -- waybar
exec-once = uwsm app -- hyprpaper

# exec-once = uwsm app -- ~/.config/hypr/scripts/power-monitor

exec-once = uwsm app -- wl-paste --type text --watch cliphist store
exec-once = uwsm app -- wl-paste --type image --watch cliphist store

exec-once = [workspace special:btop silent] uwsm app -- kitty --class btop-monitor -e btop

# Uncomment in case you have issues with screensharing
# exec-once = uwsm app -- ~/.config/hypr/scripts/xdg.sh

exec-once = uwsm finalize
