# -----------------------------------------------------
# Cursor
# -----------------------------------------------------

exec-once = hyprctl setcursor ArcDusk-cursors 24

cursor {
    inactive_timeout = 5
    hide_on_key_press = true
}
