# -----------------------------------------------------
# Cursor
# -----------------------------------------------------

exec-once = hyprctl setcursor ArcDusk-cursors 24

cursor {
    sync_gsettings_theme = true
    no_hardware_cursors = 2
    use_cpu_buffer = 2
    
    hide_on_key_press = true
    inactive_timeout = 5
    
    warp_on_change_workspace = 0
    no_break_fs_vrr = 2
    zoom_factor = 1.0
}
