# -----------------------------------------------------
# User Prefs
# Add your additional Hyprland configurations here
# -----------------------------------------------------

exec-once = sleep 300 && uwsm app -- flatpak run org.qbittorrent.qBittorrent

env = EDITOR,nvim
env = VISUAL,nvim
env = SUDO_EDITOR,nvim
env = NVIM_APPNAME,nvim-nvchad
env = NVIM_APPNAME,nvim-astro5
env = PATH,$PATH:$HOME/.local/share/bob/nvim-bin

