env = EDITOR,nvim 
env = VISUAL,nvim
env = PATH,$HOME/.local/share/bob/nvim-bin:$PATH
# env = NVIM_APPNAME,nvim-astro5
env = NVIM_APPNAME,nvim-nvchad

env = BROWSER,app.zen_browser.zen

env = HYPRCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_THEME,Bibata-Modern-Ice
exec-once=hyprctl setcursor Bibata-Modern-Ice 24
exec-once=gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'
