# -----------------------------------------------------
# User Prefs
# Add your additional Hyprland configurations here
# -----------------------------------------------------

env = EDITOR,nvim 
env = SUDO_EDITOR,nvim
env = NVIM_APPNAME,nvim-nvchad
# env = NVIM_APPNAME,nvim-astro5
exec-once = sleep 15 && uwsm app -- flatpak run org.qbittorrent.qBittorrent
