# -----------------------------------------------------
# Keyboard & Input Layout
# -----------------------------------------------------

input {
    kb_layout = us, br
    kb_variant = , abnt2
    kb_options = grp:win_space_toggle
    
    resolve_binds_by_sym = false
    numlock_by_default = true
    repeat_rate = 50
    repeat_delay = 250
    
    follow_mouse = 1
    sensitivity = 1
    accel_profile = adaptive
    force_no_accel = false
    left_handed = false
    mouse_refocus = false
    
    scroll_method = 2fg

    touchpad {
        natural_scroll = false
        disable_while_typing = true
        tap-to-click = true
        clickfinger_behavior = true
        drag_lock = false
    }
}
