# -----------------------------------------------------
# Layouts
# -----------------------------------------------------

dwindle {
    pseudotile = true
    preserve_split = true
}

binds {
  workspace_back_and_forth = false
  pass_mouse_when_bound = false

  allow_workspace_cycles = false
  focus_preferred_method = 0
}
