# -----------------------------------------------------
# Layouts
# -----------------------------------------------------

# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true
    preserve_split = true
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}

binds {
    workspace_back_and_forth = false
    pass_mouse_when_bound = false
    allow_workspace_cycles = false
    focus_preferred_method = 0
}
