# -----------------------------------------------------
# Misc Settings
# -----------------------------------------------------

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    on_focus_under_fullscreen = 1
    allow_session_lock_restore = true
    background_color = $background

    vfr = true
    vrr = 1
    key_press_enables_dpms = true
    initial_workspace_tracking = 0

    mouse_move_enables_dpms = true
    always_follow_on_dnd = true
}

# XWayland
xwayland {
  force_zero_scaling = true
}
