# -----------------------------------------------------
# General Window Layout and Colors
# -----------------------------------------------------

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 3
    col.active_border = $source_color rgba(00000050) 90deg
    col.inactive_border = rgba(00000050)
    layout = dwindle
    resize_on_border = false
}
