# -----------------------------------------------------
# Window Layout and Colors
# -----------------------------------------------------

general {
    # Espaçamentos e Bordas
    gaps_in = 5
    gaps_out = 10
    gaps_workspaces = 0
    border_size = 2

    # Cores baseadas no Matugen
    col.active_border = $primary rgba(00000000) 90deg
    col.inactive_border = rgba(00000000)

    # Comportamento
    resize_on_border = false
    allow_tearing = true
    layout = dwindle

    snap {
        enabled = false
    }
}
