##############################
### WINDOWS AND WORKSPACES ###
##############################

# Idleinhibit
windowrule = match:class = ([window]), idle_inhibit = fullscreen
windowrule = idle_inhibit fullscreen true, match:class ^(.*celluloid.*)$|^(.*mpv.*)$|^(.*vlc.*)$
windowrule = idle_inhibit fullscreen true, match:class ^(.*[Ss]potify.*)$
windowrule = idle_inhibit fullscreen true, match:class ^(.*LibreWolf.*)$|^(.*floorp.*)$|^(.*brave-browser.*)$|^(.*firefox.*)$|^(.*chromium.*)$|^(.*zen.*)$|^(.*vivaldi.*)$

windowrule {
     name = idle_media_players
     match:class = ^(vlc|mpv)$
     idle_inhibit = focus
}

windowrule {
     name = idle_youtube
     match:class = ^(firefox)$
     match:title = .*YouTube.*
     idle_inhibit = focus
}

# Only add the Core applications here
windowrule {
    name = floating_apps
    tag = +floating_apps
    match:class = ^(blueman-manager|pavucontrol-qt|com\.gabm\.satty|vlc|kvantummanager|qt[56]ct|nwg-(look|displays)|org\.kde\.ark|org\.pulseaudio\.pavucontrol|blueman-manager|nm-(applet|connection-editor)|org\.kde\.polkit-kde-authentication-agent-1|console-dropdown)$
    float = true
    center = true
    size = 720 480
}

# Common popups
windowrule {
    name = common_popups
    tag = +common_popups
    match:title = ^(Open|Open File|Select a File|Choose wallpaper|Open Folder|Save As|Library|File Upload|Authentication Required|Add Folder to Workspace|Choose Files|Confirm to replace files|File Operation Progress)(.*)$|^(.*dialog.*)$
    float = true
    center = true
    size = 800 600
}

windowrule {
    name = portal_dialogs
    tag = +portal_dialogs
    match:class = ^(org\.freedesktop\.impl\.portal\.desktop\.(hyprland|gtk)|[Xx]dg-desktop-portal-gtk)$
    float = true
    center = true
}

windowrule {
    name = picture_in_picture
    match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
    tag = +picture-in-picture
    float = true
    pin = true
    size = 640 480
    move = (monitor_w-window_w-20) (monitor_h-window_h-20)
    no_dim = on
    opaque = on
}

# Float and center file pickers
windowrule {
    name = xdg-desktop-portal-gtk
    match:class = ^(.*dialog.*|[Xx]dg-desktop-portal-gtk)$
    match:title = ^(Open.*Files?|Save.*Files?|All Files|Save)
    float = true
    center = true
    size = 640 480
}

# Kitty floating
windowrule {
    name = kitty-floating
    match:class = ^(kitty-floating)$
    match:title = ^(kitty)$
    float = on
    size = 1024 768
    center = on
}

# Gnome Calculator
windowrule {
    name = gnome-calculator
    match:class = (org.gnome.Calculator)
    float = true
    center = true
    size = 640 480
}

# Loupe
windowrule {
    name = loupe
    match:class = (org.gnome.Loupe)
    float = true
    center = true
    size = 1024 768
}
