# -----------------------------------------------------
# General workspace rules
# Example rules (from https://wiki.hyprland.org/Configuring/Workspace-Rules/)
# -----------------------------------------------------

