# -----------------------------------------------------
# General Workspace Rules
# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# -----------------------------------------------------

# workspace = 1, layout:master, layoutopt:orientation:left
# workspace = special:scratchpad, on-created-empty:kitty
# workspace = special:btop, on-created-empty:kitty --class kitty-floating -e btop
# workspace = name:coding, rounding:false, decorate:false, gapsin:0, gapsout:0, border:false, monitor:DP-1

workspace = m[eDP-1], layout:master, layoutopt:orientation:left
workspace = m[HDMI-A-1], layout:scrolling, layoutopt:direction:right
