Net/ThemeName "Material-Dark"
Net/IconThemeName "Colloid-Dark"
Gtk/CursorThemeName "ArcDusk-cursors"
Net/EnableEventSounds 1
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
