$image = Null

$background = rgba(2c273dff)

$error = rgba(e677b5ff)

$error_container = rgba(413c52ff)

$inverse_on_surface = rgba(2c273dff)

$inverse_primary = rgba(bd8ff5ff)

$inverse_surface = rgba(c1c0efff)

$on_background = rgba(c1c0efff)

$on_error = rgba(1e192bff)

$on_error_container = rgba(e677b5ff)

$on_primary = rgba(1e192bff)

$on_primary_container = rgba(c1c0efff)

$on_primary_fixed = rgba(1e192bff)

$on_primary_fixed_variant = rgba(413c52ff)

$on_secondary = rgba(1e192bff)

$on_secondary_container = rgba(c1c0efff)

$on_secondary_fixed = rgba(1e192bff)

$on_secondary_fixed_variant = rgba(413c52ff)

$on_surface = rgba(c1c0efff)

$on_surface_variant = rgba(9e9cbeff)

$on_tertiary = rgba(1e192bff)

$on_tertiary_container = rgba(c1c0efff)

$on_tertiary_fixed = rgba(1e192bff)

$on_tertiary_fixed_variant = rgba(413c52ff)

$outline = rgba(69647dff)

$outline_variant = rgba(555167ff)

$primary = rgba(bd8ff5ff)

$primary_container = rgba(413c52ff)

$primary_fixed = rgba(bd8ff5ff)

$primary_fixed_dim = rgba(859afcff)

$scrim = rgba(1e192bff)

$secondary = rgba(859afcff)

$secondary_container = rgba(413c52ff)

$secondary_fixed = rgba(859afcff)

$secondary_fixed_dim = rgba(555167ff)

$shadow = rgba(1e192bff)

$source_color = rgba(bd8ff5ff)

$surface = rgba(252135ff)

$surface_bright = rgba(413c52ff)

$surface_container = rgba(2c273dff)

$surface_container_high = rgba(252135ff)

$surface_container_highest = rgba(413c52ff)

$surface_container_low = rgba(2c273dff)

$surface_container_lowest = rgba(1e192bff)

$surface_dim = rgba(2c273dff)

$surface_tint = rgba(bd8ff5ff)

$surface_variant = rgba(413c52ff)

$tertiary = rgba(e677b5ff)

$tertiary_container = rgba(413c52ff)

$tertiary_fixed = rgba(e677b5ff)

$tertiary_fixed_dim = rgba(555167ff)

