
$background = rgba(131313ff)

$error = rgba(ffb4abff)

$error_container = rgba(da342eff)

$inverse_on_surface = rgba(303030ff)

$inverse_primary = rgba(005e3eff)

$inverse_surface = rgba(e2e2e2ff)

$on_background = rgba(e2e2e2ff)

$on_error = rgba(4b0002ff)

$on_error_container = rgba(ffffffff)

$on_primary = rgba(002717ff)

$on_primary_container = rgba(ffffffff)

$on_primary_fixed = rgba(002113ff)

$on_primary_fixed_variant = rgba(004a30ff)

$on_secondary = rgba(10251aff)

$on_secondary_container = rgba(ffffffff)

$on_secondary_fixed = rgba(0a1f15ff)

$on_secondary_fixed_variant = rgba(2f4539ff)

$on_surface = rgba(f4f4f4ff)

$on_surface_variant = rgba(c6c6c6ff)

$on_tertiary = rgba(00242fff)

$on_tertiary_container = rgba(ffffffff)

$on_tertiary_fixed = rgba(001f28ff)

$on_tertiary_fixed_variant = rgba(1c4553ff)

$outline = rgba(9f9f9fff)

$outline_variant = rgba(747474ff)

$primary = rgba(70dba8ff)

$primary_container = rgba(00855aff)

$primary_fixed = rgba(8cf7c2ff)

$primary_fixed_dim = rgba(70dba8ff)

$scrim = rgba(000000ff)

$secondary = rgba(b4ccbcff)

$secondary_container = rgba(637a6cff)

$secondary_fixed = rgba(d0e8d8ff)

$secondary_fixed_dim = rgba(b4ccbcff)

$shadow = rgba(000000ff)

$source_color = rgba(63a885ff)

$surface = rgba(131313ff)

$surface_bright = rgba(404040ff)

$surface_container = rgba(242424ff)

$surface_container_high = rgba(2f2f2fff)

$surface_container_highest = rgba(3a3a3aff)

$surface_container_low = rgba(1d1d1dff)

$surface_container_lowest = rgba(0a0a0aff)

$surface_dim = rgba(131313ff)

$surface_tint = rgba(70dba8ff)

$surface_variant = rgba(474747ff)

$tertiary = rgba(a4cddeff)

$tertiary_container = rgba(537a89ff)

$tertiary_fixed = rgba(c0e9faff)

$tertiary_fixed_dim = rgba(a4cddeff)


