$image = Null

$background = rgba(583d58ff)

$error = rgba(fc8893ff)

$error_container = rgba(ff1a6fff)

$inverse_on_surface = rgba(6f5b6cff)

$inverse_primary = rgba(c44ad9ff)

$inverse_surface = rgba(e1bdd9ff)

$on_background = rgba(e1bdd9ff)

$on_error = rgba(e80051ff)

$on_error_container = rgba(e6e6e6ff)

$on_primary = rgba(a300beff)

$on_primary_container = rgba(e6e6e6ff)

$on_primary_fixed = rgba(86009eff)

$on_primary_fixed_variant = rgba(c400e4ff)

$on_secondary = rgba(8e2f9cff)

$on_secondary_container = rgba(e6e6e6ff)

$on_secondary_fixed = rgba(86019eff)

$on_secondary_fixed_variant = rgba(a04eabff)

$on_surface = rgba(e1bdd9ff)

$on_surface_variant = rgba(c7a8c2ff)

$on_tertiary = rgba(a17800ff)

$on_tertiary_container = rgba(876400ff)

$on_tertiary_fixed = rgba(8d6700ff)

$on_tertiary_fixed_variant = rgba(ba8f00ff)

$outline = rgba(947b92ff)

$outline_variant = rgba(8e788eff)

$primary = rgba(f87bffff)

$primary_container = rgba(c44fd8ff)

$primary_fixed = rgba(ffa4fdff)

$primary_fixed_dim = rgba(f87bffff)

$scrim = rgba(1a1a1aff)

$secondary = rgba(f085f5ff)

$secondary_container = rgba(a75faeff)

$secondary_fixed = rgba(ffa4fdff)

$secondary_fixed_dim = rgba(f085f5ff)

$shadow = rgba(1a1a1aff)

$source_color = rgba(bc37d3ff)

$surface = rgba(583d58ff)

$surface_bright = rgba(786576ff)

$surface_container = rgba(614e61ff)

$surface_container_high = rgba(6b5768ff)

$surface_container_highest = rgba(746271ff)

$surface_container_low = rgba(5e465eff)

$surface_container_lowest = rgba(563058ff)

$surface_dim = rgba(583d58ff)

$surface_tint = rgba(f87bffff)

$surface_variant = rgba(856d84ff)

$tertiary = rgba(f4bf34ff)

$tertiary_container = rgba(d3a426ff)

$tertiary_fixed = rgba(ffd883ff)

$tertiary_fixed_dim = rgba(f4bf34ff)

