general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 1. Diminuir Backlight do Teclado
listener { 
    timeout = 140
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

# 2. Diminuir Brilho da Tela
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 1
    on-resume = brightnessctl -r
}

# 3. Bloquear Sessão
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 4. Desligar Tela (DPMS)
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 5. Suspender (Apenas se NÃO houver áudio tocando)
listener {
    timeout = 600
    on-timeout = pactl list sinks | grep -q "State: RUNNING" || systemctl suspend
}
