#  _   _                  _                 _
# | | | |_   _ _ __  _ __| | __ _ _ __   __| |
# | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` |
# |  _  | |_| | |_) | |  | | (_| | | | | (_| |
# |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#        |___/|_|
#

# -- colors --
source = ./colors.conf

# -- variables --
source = ./configs/variables.conf

# -- monitors --
source = ./configs/monitors.conf

# -- binds --
source = ./configs/keybinds.conf

# -- window rules --
source = ./configs/windowrules.conf

# -- animations --
source = ./configs/animations.conf

# -- dwindle --
source = ./configs/dwindlelayout.conf

# -- permissions --
source = ./configs/permissions.conf

# -- environment variables --
source = ./configs/environment.conf

# -- executing --
source = ./configs/autostart.conf

# -- custom --
source = ./configs/custom.conf
