foreground            #f8f8f2
background            #282a36
selection_foreground  #44475a
selection_background  #ff79c6

url_color             #282a36

# Black
color0   #21222c
color8   #bd93f9

# Red
color1   #fd5186
color9   #e058e4

# Green
color2   #00fba0
color10  #d8d9ff

# Yellow
color3   #fff68c
color11  #fbeeff

# Blue
color4   #bd93f9
color12  #bd93f9

# Magenta
color5   #f37cdf
color13  #db85ff

# Cyan
color6   #bae0ff
color14  #dad7ff

# White
color7   #f8f8f2
color15  #44475a

# Cursor colors
cursor #f8f8f2
cursor_text_color #21222c

# Tab bar colors
active_tab_foreground #282a36
active_tab_background #bd93f9
inactive_tab_foreground #f8f8f2
inactive_tab_background #44475a

# Marks
mark1_foreground #282a36
mark1_background #bd93f9
mark2_foreground #282a36
mark2_background #ff79c6
mark3_foreground #282a36
mark3_background #ffb86c

# Splits/Windows
active_border_color #ff79c6
inactive_border_color #282a36
bell_border_color #ff5a00
