foreground            #cdd6f4
background            #1e1e2e
selection_foreground  #313244
selection_background  #45475a

url_color             #cba6f7


color0 #4b3199

color1 #412c90

color2 #5b42b1

color3 #6f60be

color4 #8c7ec9

color5 #e5e4fd

color6 #fdf0f0

color7 #d7d0ff

color8 #fe92cf

color9 #ffc3b0

color10 #ffead2

color11 #97fac2

color12 #96f6fa

color13 #b6c3ff

color14 #d8b8ff

color15 #fbdae2


# Cursor colors
cursor #cdd6f4
cursor_text_color #181825

# Tab bar colors
active_tab_foreground #11111b
active_tab_background #cba6f7
inactive_tab_foreground #cdd6f4
inactive_tab_background #313244

# Marks
mark1_foreground #11111b
mark1_background #cba6f7
mark2_foreground #11111b
mark2_background #89b4fa
mark3_foreground #11111b
mark3_background #f38ba8

# Splits/Windows
active_border_color #cba6f7
inactive_border_color #11111b
bell_border_color #ff5a00
