cursor #f5f4fa
cursor_text_color #c4c6d2

foreground            #f5f4fa
background            #121318
selection_foreground  #152039
selection_background  #bbc6e6
url_color             #b0c6ff

# black
color8   #f5f4fa
color0   #4c4c4c

# red
color1   #ffb4ab
color9   #c49ea0

# green
color2   #f5f4fa
color10  #9ec49f

# yellow
color3   #aca98a
color11  #c4c19e

# blue
/* color4  #8f8aac */
color4  #b0c6ff
color12 #a39ec4

# magenta
color5   #ffb4ab
color13  #c49ec4

# cyan
color6   #f5f4fa
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0