cursor #f4f4f4
cursor_text_color #c6c6c6

foreground            #f4f4f4
background            #131313
selection_foreground  #10251a
selection_background  #b4ccbc
url_color             #70dba8

# black
color8   #f4f4f4
color0   #4c4c4c

# red
color1   #ffb4ab
color9   #c49ea0

# green
color2   #f4f4f4
color10  #9ec49f

# yellow
color3   #aca98a
color11  #c4c19e

# blue
/* color4  #8f8aac */
color4  #70dba8
color12 #a39ec4

# magenta
color5   #ffb4ab
color13  #c49ec4

# cyan
color6   #f4f4f4
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0