cursor #fff2ef
cursor_text_color #e7bdb4

foreground            #fff2ef
background            #200f0b
selection_foreground  #470800
selection_background  #ffb4a4
url_color             #ffb4a4

# black
color8   #fff2ef
color0   #4c4c4c

# red
color1   #ffb4ab
color9   #c49ea0

# green
color2   #fff2ef
color10  #9ec49f

# yellow
color3   #aca98a
color11  #c4c19e

# blue
/* color4  #8f8aac */
color4  #ffb4a4
color12 #a39ec4

# magenta
color5   #ffb4ab
color13  #c49ec4

# cyan
color6   #fff2ef
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0