cursor #ffffff
cursor_text_color #dddddd

foreground            #e3e3e3
background            #1e1e1e
selection_foreground  #443b51
selection_background  #d0c4dc
url_color             #5f3a93

# black
color8   #ffffff
color0   #1e1e1e

# red
color1   #ff5858
color9   #de748c

# green
color2   #52ff7f
color10  #35ad7c

# yellow
color3   #f3fc8d
color11  #ad9a18

# blue
color4   #bf95fc
color12  #a883dc

# magenta
color5   #ff7bc9
color13  #c879bf

# cyan
color6   #8cebff
color14  #0ca4d2

# white
color15  #dddddd
color7   #e3e3e3
