foreground            #e3e3e3
background            #1e1e1e
selection_foreground  #443b51
selection_background  #d0c4dc

url_color             #5f3a93

# Black
color8   #ffffff
color0   #1e1e1e

# Red
color1   #ee75c4
color9   #c879c0

# Green
color2   #00f9f8
color10  #34a3de

# Yellow
color3   #fff1f4
color11  #e87878

# Blue
color4   #bf95fc
color12  #a883dc

# Magenta
color5   #e982f2
color13  #b97ed1

# Cyan
color6   #d0ddff
color14  #7296ea

# White
color15  #dddddd
color7   #e3e3e3

# Cursor colors
cursor #ffffff
cursor_text_color #1e1e1e

# Tab bar colors
active_tab_foreground #3d0e75
active_tab_background #e9d5ff
inactive_tab_foreground #000000
inactive_tab_background #a883dc

# Marks
mark1_foreground #250053
mark1_background #eddcff
mark2_foreground #20152f
mark2_background #ecddf8
mark3_foreground #3b0918
mark3_background #ffdae0

# Splits/Windows
active_border_color #e9d5ff
inactive_border_color #3d0e75
bell_border_color #ff5a00
