cursor #dde1e6
cursor_text_color #f2f4f8

foreground            #dde1e6
background            #121212
selection_foreground  #161616
selection_background  #08bdba
url_color             #ff7eb6

color0   #161616
color1   #ff7178
color2   #9fff7e
color3   #ffe171
color4   #f25f9f
color5   #760838
color6   #ff7eb6
color7   #ffeff6
color8   #a5999e
color9   #ff9ea3
color10  #bcffa4
color11  #ffeba4
color12  #ff91c0
color13  #ffa4cb
color14  #ffc4de
color15  #fff8fb
