[config]
fallback_color = "#89b4fa"
prefer = "closest-to-fallback"
caching = false

[config.custom_colors]
cyan="#8be9fd"
green="#50fa7b"
orange="#ffb86c"
pink="#ff79c6"
purple="#bd93f9"
red="#ff5555"
yellow="#f1fa8c"

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.fuzzel]
input_path = './templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/colors.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/colors.cava'
post_hook = 'pkill -USR1 cava || true'

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme "Dracula"; gsettings set org.gnome.desktop.interface gtk-theme "Dracula"'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.qt5ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.yazi]
input_path = './templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.zathura]
input_path = './templates/zathura-colors'
output_path = '~/.config/zathura/zathurarc'

[templates.swaync]
input_path = "./templates/colors.css"
output_path = "~/.config/swaync/colors.css"
post_hook = "swaync-client -rs"

[templates.nvim-astro5]
input_path = './templates/nvim-base16.lua'
output_path = '~/.config/nvim-astro5/lua/plugins/base16-prox-max.lua'

[templates.nvim-nvchad]
input_path = './templates/nvim-base46.lua'
output_path = '~/.local/share/nvim-nvchad/lazy/base46/lua/base46/themes/chadwal.lua'
post_hook = 'pkill -SIGUSR1 nvim'
