[config]
caching = false

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.lua'
output_path = '~/.config/hypr/colors.lua'
post_hook = 'hyprctl reload'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/colors.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/config'
post_hook = 'pkill -USR1 cava || true'

[templates.zathura]
input_path = '~/.config/matugen/templates/zathura-colors'
output_path = '~/.config/zathura/zathurarc'

[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.nvim]
input_path = '~/.config/matugen/templates/nvim-colors.vim'
output_path = '~/.config/nvim/colors/matugen.vim'
post_hook = 'pkill -SIGUSR1 nvim'

[templates.nvim-astro5]
input_path = '~/.config/matugen/templates/nvim-base16.lua'
output_path = '~/.config/nvim-astro6/lua/plugins/base16-prox-max.lua'

[templates.nvim-nvchad]
input_path = '~/.config/matugen/templates/nvim-base46.lua'
output_path = '~/.local/share/nvim-nvchad/lazy/base46/lua/base46/themes/matugen.lua'
post_hook = 'pkill -SIGUSR1 nvim'

[templates.zellij]
input_path = '~/.config/matugen/templates/zellij-theme.kdl'
output_path = '~/.config/zellij/themes/matugen.kdl'
post_hook = 'touch ~/.config/zellij/config.kdl'
