#!/bin/bash

killall -q waybar

while pgrep -u $UID -x waybar >/dev/null; do sleep 1; done

CONFIG="$HOME/.config/waybar/config.jsonc"
STYLE="$HOME/.config/waybar/style.css"

waybar -c "$CONFIG" -s "$STYLE" >/dev/null 2>&1 &
