#!/usr/bin/env bash

BASE_DIR="${1:-$HOME}"

QUERY=$(fuzzel --dmenu --prompt "Search text: ")

[ -z "$QUERY" ] && exit 0

RESULT=$(rg --line-number --column --no-heading --color=never \
  --smart-case \
  --hidden --follow \
  --glob '!.git/*' \
  --glob '!node_modules/*' \
  --glob '!target/*' \
  "$QUERY" "$BASE_DIR" |
  fuzzel --dmenu --prompt "Results: ")

[ -z "$RESULT" ] && exit 0

FILE=$(echo "$RESULT" | cut -d: -f1)
LINE=$(echo "$RESULT" | cut -d: -f2)
COL=$(echo "$RESULT" | cut -d: -f3)

foot -e nvim +"call cursor($LINE, $COL)" "$FILE" &
