#!/usr/bin/env bash

declare -A colors

colors=(
  ["󰏘 Cyan"]="#8be9fd"
  ["󰏘 Green"]="#50fa7b"
  ["󰏘 Orange"]="#ffb86c"
  ["󰏘 Pink"]="#ff79c6"
  ["󰏘 Purple"]="#bd93f9"
  ["󰏘 Red"]="#ff5555"
  ["󰏘 Yellow"]="#f1fa8c"
)

choice=$(for name in "${!colors[@]}"; do echo "$name"; done | sort |
  fuzzel --dmenu --prompt="󱓟 Choose a color (or type HEX color): " --width=30)

[ -z "$choice" ] && exit 0

if [[ ${colors[$choice]} ]]; then
  hex_color=${colors[$choice]}
else
  if [[ $choice =~ ^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$ ]]; then
    hex_color=$choice
  else
    notify-send "Color Selector" "Invalid HEX code!" --icon=error
    exit 1
  fi
fi

notify-send "Color Selector" "Generating theme for the color $hex_color..." --icon=color-management
matugen -t scheme-rainbow \
  --contrast 0.5 \
  -m dark \
  -r nearest \
  --continue-on-error \
  --fallback-color "#bd93f9" \
  --lightness-dark 0.05 \
  color hex "$hex_color"
notify-send "Color Selector" "Color $hex_color applied successfully!" -i color-select
