#!/usr/bin/env bash

TERMINAL="kitty"

service=$(systemctl --user list-unit-files --type=service --no-pager 2>/dev/null |
  awk 'NR>1 {print $1}' |
  fuzzel --dmenu --prompt "Select a service:") || exit 0

[ -z "$service" ] && exit 0

action=$(echo -e "Start\nStop\nReload\nStatus" |
  fuzzel --dmenu --prompt "Choose the action to $service:") || exit 0

[ -z "$action" ] && exit 0

action=$(echo "$action" | tr '[:upper:]' '[:lower:]')

$TERMINAL -e bash -c "systemctl --user $action $service; exec bash"
