#!/usr/bin/env bash

raw_colors="
  red = '#FF5555',
  baby_pink = '#FF7EB6',
  pink = '#FF6BCB',
  green = '#25be6a',
  vibrant_green = '#20E3B2',
  nord_blue = '#78A9FF',
  blue = '#2CCCFF',
  yellow = '#ffe731',
  sun = '#F2FA95',
  purple = '#BE95FF',
  dark_purple = '#a166f6',
  teal = '#33B1FF',
  orange = '#ffa332',
  cyan = '#3DDBD9',
"

declare -A colors

while read -r name hex; do
  [[ -z "$name" || -z "$hex" ]] && continue
  colors["$name"]="$hex"
done < <(echo "$raw_colors" | sed -E "s/[[:space:]]*=[[:space:]]*/ /; s/['\",]//g")

choice=$(for name in "${!colors[@]}"; do echo "$name"; done | sort |
  fuzzel --dmenu --prompt="󱓟 Choose a color: " --width=30)

[ -z "$choice" ] && exit 0

if [[ ${colors[$choice]} ]]; then
  hex_color=${colors[$choice]}
else
  # Se o que foi digitado for um HEX válido que não está na lista
  if [[ $choice =~ ^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$ ]]; then
    hex_color=$choice
  else
    notify-send "Color Selector" "Invalid HEX code!" --icon=error
    exit 1
  fi
fi

notify-send "Color Selector" "Generating theme for $hex_color..." --icon=color-management

matugen -t scheme-rainbow \
  --contrast 0.5 \
  -m dark \
  -r nearest \
  --continue-on-error \
  --fallback-color "#bd93f9" \
  --lightness-dark 0.05 \
  color hex "$hex_color"

notify-send "Color Selector" "Color $hex_color applied successfully!" -i color-select
