#!/usr/bin/env bash

if [[ -z $(hyprctl workspaces | grep special:magic) ]]; then
  hyprctl eval 'hl.dispatch(hl.dsp.window.move({ workspace = "special:magic" }));hl.dispatch(hl.dsp.workspace.toggle_special("magic"))'
else
  hyprctl eval 'hl.dispatch(hl.dsp.workspace.toggle_special("magic"));hl.dispatch(hl.dsp.window.move({ workspace = "+0" }))'
fi
