#!/usr/bin/env python3

import os
import subprocess
import sys

THEMES_DIR = os.path.expanduser("~/.config/matugen/themes")


def get_themes():
    if not os.path.exists(THEMES_DIR):
        print(f"Error: Directory {THEMES_DIR} not found.")
        sys.exit(1)

    return [f for f in os.listdir(THEMES_DIR) if f.endswith(".json")]


def main():
    themes = get_themes()

    if not themes:
        print("No JSON files found in themes directory.")
        sys.exit(1)

    themes_list = "\n".join(themes)

    run_rofi = subprocess.run(
        ["rofi", "-dmenu", "-i", "-p", "Select Theme:", "-replace"],
        input=themes_list,
        capture_output=True,
        text=True,
    )

    selected_theme = run_rofi.stdout.strip()

    if not selected_theme:
        print("Operation cancelled.")
        sys.exit(0)

    theme_path = os.path.join(THEMES_DIR, selected_theme)

    if not os.path.exists(theme_path):
        print(f"Error: File '{selected_theme}' not found.")
        sys.exit(1)

    try:
        subprocess.run(
            ["systemctl", "--user", "stop", "hyprpaper.service"], check=False
        )

        subprocess.run(
            ["matugen", "json", theme_path],
            check=True,
        )

        print(f"Success: Theme '{selected_theme}' applied!")

    except subprocess.CalledProcessError as e:
        print(f"Error when running Matugen: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")


if __name__ == "__main__":
    main()
